### ISSUE TITLE
"acf.get_fields is not a function" after upgrade to 5.7 beta

### ISSUE THREAD

**Issue by krishaamer** [AdvancedCustomFields/acf#29]
While running acf_form on the frontend:

`VM2581 input.js:484 Uncaught TypeError: acf.get_fields is not a function
    at VM2581 input.js:484
    at _runHook (VM2576 acf-input.js:2299)
    at Object.doAction (VM2576 acf-input.js:2125)
    at Object.acf.doAction (VM2576 acf-input.js:819)
    at HTMLDocument.<anonymous> (VM2576 acf-input.js:2045)
    at i (VM2555 jquery-1.12.4.min.js:2)
    at Object.fireWith [as resolveWith] (VM2555 jquery-1.12.4.min.js:2)
    at Function.ready (VM2555 jquery-1.12.4.min.js:2)
    at HTMLDocument.K (VM2555 jquery-1.12.4.min.js:2)`

**Comment by elliotcondon** [comment]
Hi @krishaamer 

Thanks for the bug report.

Yes, I need to add in compatibility for the existing `acf.get_fields()` function.
- This function no longer exists (currently) but has been used in documentation, so I'm happy to add it back in.

The core plugin shouldn't be calling this function, so it is most likely that you have a 3rd party ACF plugin active - is this possible?

if so, please let me know which one, so that I can test this too.

**Comment by elliotcondon** [comment]
Hi @krishaamer 

I've just performed some testing and added in the missing `acf.get_fields()` function. 
Everything looks to be working for me, can you please test this out?
- I'll attached updated .js files for you to drop into your **acfpro/assets/js** folder.
[Archive.zip](https://github.com/AdvancedCustomFields/acf/files/1867047/Archive.zip)

Thanks
Elliot
